stages:
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download/dataset.csv
  build:
    cmd: python stages/02_build.py
    deps:
      - stages/02_build.py
      - download/dataset.csv
    outs:
      - brick/aqsoldb.parquet
